### ISSUE TITLE
Where do I get Tungsten?

### ISSUE THREAD

**Issue by GreenSh4dow** [MyM-ModpackTeam/GalacticScience#105]
Electrical Ages needs Tungsten but i cant find Tungsten on my own Server or Singleplayer? 

Sorry if this is bad english

Greetings
GreenSh4dow

**Comment by Zeldinator** [comment]
You have to decompose Nether Items for Tungsten - the easiest way to do so is by decomposing Netherrack with an Ex Nihilo Barrel filled with Lava and some Redstone. You have only a small chance to get Tungsten, but since you only need 31 to create a fusion chamber, you can get them in around 20 mins.

**Comment by johnfg12** [comment]
u guys ok?

**Comment by Zeldinator** [comment]
GreenSh4adow never replied - i guess he is alright.

**Comment by johnfg12** [comment]
il close this then :)

**Comment by Werwolfi** [comment]
Its not ok, its still an issue. your answer was not correct there are 2 tungsten in the game. please dont just reply cause u may know the answer. only reply if you know the answer

**Comment by Zeldinator** [comment]
Hey, I haven't replied because i, citation "may know the answer", I have replied cause I tried to help. Of course, it was a misunderstanding, but don't accuse me that i would just "guess" answers, since i spent nearly 20 mins to find the recipes and the amount of stuff you need. Please.

Back to Tungsten: Yes, I spent some time finding a recipe for EA Tungsten, but you were right - there is no way to get it: Neither is it mineable nor is it craftable. And since it's pretty essential in EA, thats a rather big bug.

I'd suggest to sync up the MineChem Tungsten Element with the EA Tungsten Ingot, like 16 to 1, similar to Iron, Gold...

**Comment by drz2k** [comment]
Im more for kicking EA out if we make a new mayor version. Its a very interesting mod but documentation and development is kinda horrible. Thats why it was never actually integrated into GS.

As it stands, its a mod outside of all balanced/featured/quest stuff that has no real legitimation why its there. Its a leftover from alpha/beta state.

**Comment by Zeldinator** [comment]
I think it would be a pity if you kicked out EA - at the Point of View of an Guy, who is into electronic circuits, this Mod is just AWESOME. Yes, the it's documentation could be better, but I'd suggest to give it at least a fair chance - as far as i know, there is not a single Quest belonging EA circuits in the whole pack. And in my opinion it also fits to the scientific style of GS, like Minechem does.

Sounds perhaps a bit rude, but i wonder how it would look if EA would be the only way to transport Energy in the Modpack...
