### ISSUE TITLE
Galacticraft Science - Tardis Issue - Game Crashes

### ISSUE THREAD

**Issue by Peter-Bohus** [MyM-ModpackTeam/GalacticScience#131]
Hello, I would like to ask why I can't use my tardis recaller stick to call my tardis. When I use it the tardis disappears and it says tardis inbound but it doesn't come. It just disappears so I have to use the tardis recalled block to call it. Also I have another issue regarding the tardis; when I try to build inside the tardis now I get a crash report and the game just closes... The crash report is : http://pastebin.com/twu9W656
Thank you for your help and time to read this.
Hope you can help me with this.

**Comment by drz2k** [comment]
https://github.com/DarkholmeTenk/TardisModIssues/issues

**Comment by Peter-Bohus** [comment]
So what's the issue?

**Comment by Peter-Bohus** [comment]
What do I do?

**Comment by drz2k** [comment]
This is a modPACK issuetracker where we can try to give free support or fix issues with our modpack.

You are experiencing a crash from a mod. I can't fix the mod since I dont make it, thats why I linked you the issuetracker of the crashing mod.

Also more information would be helpfull like what you try to build, which dim you are in, which version of pack and mod you are using ..

**Comment by Peter-Bohus** [comment]
It's in the tardis dimension inside the large room when I try to build in there.. I am just placing blocks like chiselled cobble and dirt for a tree farm

**Comment by drz2k** [comment]
You are still reporting this to the modPACK makers, not the mod creator who could actually fix things.

**Comment by Peter-Bohus** [comment]
How do I report it to them I think I did do that now...

**Comment by drz2k** [comment]
My first comment was the link to the tardis mod issuetracker ...

**Comment by Peter-Bohus** [comment]
Ok so I did it then I made a new thread on that link...
