### ISSUE TITLE
No recipe for galactic craft aluminium

### ISSUE THREAD

**Issue by SluttyPenguin** [MyM-ModpackTeam/GalacticScience#162]
We need 16 aluminium for a space station but we need galactic craft aluminium,EX Nihilo one doesn't work. And there's no way to make galactic craft one!

**Comment by kindlich** [comment]
Did you try using the usual ore dictionary converting methods?
Not sure, but I think there was a way involving minechem

**Comment by SluttyPenguin** [comment]
We tried using minechem it still gives the Ex Nihilo one.

**Comment by kindlich** [comment]
Is this issue occuring at the MyM Network or on an own server?
MyM could have deliberately disabled the recipe as every Space station gets its own Dimension (and Dimension creation is disallowed on the network)

If this Issue is happening at the MyM-Network, please close this issue and instead submit a ticket using the /ticket create comman ingame

**Comment by SluttyPenguin** [comment]
On my own server

**Comment by Sir-Will** [comment]
Should be obtainable on the mars and via Ex Nihilo.
