### ISSUE TITLE
lost

### ISSUE THREAD

**Issue by hmbigburt** [MyM-ModpackTeam/GalacticScience#49]
i personally believe some form of mapping system (voxel etc) other than that a creative mode so i could design basses would be nice but not essential thanx.

**Comment by Slind14** [comment]
you are free to add whatever mods you like to your client. If there is one that you think would be nice in the pack in general, a more in-depth explanation would be nice.
How does it fit into the pack?
What is unique (not covered by other mods in the pack)?

**Comment by jaspercayne** [comment]
[JourneyMap](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278348-journeymap-5-1-1-realtime-mapping-in-game-or-in-a) would be a good addition to the pack since it is highly configurable and could be pre-configured to not allow cave mapping or displaying mobs on the radar, depending on how the pack devs feel about said options being "cheaty". It is also a good low resource mapping option on servers as well which fits in nicely with having the server support large numbers of players.

**Comment by Slind14** [comment]
Journey Map tends to be quite resource hungry, with the pack focusing on being light weight, we had decided against it. But you are free to add it, if you like it.

**Comment by jaspercayne** [comment]
I thought the maps were pre-generated for the most part, so I expected the map to be able to be created and distributed with the pack itself, lessening the resource cost of generating on the fly. If I was mistaken then by all means correct me. I do acknowledge the size increase of distributing the map with the pack but thought it might be an option you could present to your users.

**Comment by hmbigburt** [comment]
if there is a copy of the maps could i get a link plz

**Comment by SirWilli** [comment]
The map is not pregenerated, only few chunks with the starter base is.

**Comment by SirWilli** [comment]
I don't understand your issue description here. Do you want to create a own starter base in creative?

**Comment by jaspercayne** [comment]
I actually am a little curious about how you did the templates myself. I enjoy the observatory but find the lack of sand for starting out a bit problematic...

**Comment by SirWilli** [comment]
Just go into creative mode via open to lan and enable cheats.
