### ISSUE TITLE
Update modular systems

### ISSUE THREAD

**Issue by goreae** [MyM-ModpackTeam/GalacticScience#58]
I noticed that modular systems is severely outdated. That was because the newer versxion of it removed the modular storage entirely. However, version 2.2.0 of the mod added the storage system back in. Now with an expansion that allows you to actually search the thing instead of having an amorphous blob of items. I was just hoping y'all could add in the more recent version for a better modular storage.

**Comment by drz2k** [comment]
Modular systems is only kept as legacy since the update (better call it a rewrite) changes all the blocks. So every installation already in worlds (including maybe the players main storage!) would simply vanish.

Feel free to update for yourself on new fresh worlds you create but until the point we HAVE to push an update that requires new worlds, this wont happen :)
