### ISSUE TITLE
Outdated mods

### ISSUE THREAD

**Issue by tterrag1098** [MyM-ModpackTeam/GalacticScience#76]
- [x] [SuperMassiveTech](http://minecraft.curseforge.com/projects/super-massive-tech/files/2273970) (I released an update to fix your issue ;) ) 
- [x] [EnderIO](http://minecraft.curseforge.com/projects/ender-io/files/2271075)
- [x] [EnderCore (new)](http://minecraft.curseforge.com/projects/endercore/files/2266611)
- [x] [Chisel](http://minecraft.curseforge.com/projects/chisel/files/2269360)

All by me (and company). With the fix to SMT this should be possible now :)

**Comment by Slind14** [comment]
:+1:

**Comment by SirWilli** [comment]
Thanks =)

**Comment by tterrag1098** [comment]
Also, I noticed that the ExU version we have is pretty outdated as well (5 versions).

**Comment by tterrag1098** [comment]
Refined Relocation is also extremely outdated.

**Comment by SirWilli** [comment]
Hm, the latest RefinedRelocation version I can find is 1.1.12 http://minecraft.curseforge.com/projects/refined-relocation/files
Where did you find a newer version?

Same with ExtraUitlties.

**Comment by tterrag1098** [comment]
In the latest pack version i see ExU 1.2.8 (Latest is 1.2.12 I think) and RR 1.0.8b (Latest is 1.1.12)

**Comment by tterrag1098** [comment]
Seems you committed an update for them, but it's not in the pack.

**Comment by SirWilli** [comment]
Are you playing via FTB Launcher? We haven't pushed the update there yet.

**Comment by tterrag1098** [comment]
No, I am on CurseVoice. Is the pack released anywhere else?

**Comment by tterrag1098** [comment]
On version 1.4.18 on CV and you can see the outdated ExU

![](http://puu.sh/mn93k.png)

**Comment by Slind14** [comment]
We have it on our private launcher. We deploy it on there and on the server and once everything is working fine push it to FTB which gets synced to curse. Due to the star explosion issue we have left the ftb version behind a bit. Once we have the new version with the latest mods on server for about a week without issues we will push it to ftb/curse. This has proven to be quite helpful and preventing players outside our control (we can rollback the server) from loss and game breaking bugs. If you would like to play the latest version you can either download the github release or use the MyM Launcher.

**Comment by Slind14** [comment]
https://github.com/MyM-ModpackTeam/GalacticScience/releases
